version: '3'

services:
  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: unless-stopped
    environment:
        - TZ=Europe/Brussels
    ports:
        - "8000:8000" # HTTP
        - "8443:8443" # HTTPS
        - "8123:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - ./docker/crafty/backups:/crafty/backups
        - ./docker/crafty/logs:/crafty/logs
        - ./docker/crafty/servers:/crafty/servers
        - ./docker/crafty/config:/crafty/app/config
        - ./docker/crafty/import:/crafty/import
